on: push
name: SpeakDailer on Push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          # port: 21 # todo replace with your web host's FTPS port
          # server-dir: /home/app2weqoute3/www/

      - name: Send Slack notification on success
        if: success()
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Code Deployed Successfully",
            "username": "GitHub Actions",
            "attachments": [
              {
                "color": "good",
                "title": "Repo",
                "text": "${{ github.repository }}"
              },
              {
                "color": "good",
                "title": "Branch",
                "text": "${{ github.ref }}"
              }
            ]
          }' $SLACK_WEBHOOK_URL
